* Documentator - design notes
Lo scopo di questo file è delineare i principali obiettivi di sviluppo ed i
problemi che incontriamo nello sviluppo della libreria.
* Problemi di ordine organizzativo
** Modello di sviluppo
Per quanto riguarda il modello di sviluppo, consiglio di usare un modello di
organizzazione dei branch basato su [[http://nvie.com/posts/a-successful-git-branching-model/][questo workflow]]. Potete anche lasciare a me
i dettagli, la sintesi è che vi sono sempre la branch `master` su cui vive il
codice nella versione funzionante, la branch `develop` su cui vengono integrate
le features di sviluppo, e infine una branch per ogni feature che si va a
risolvere. Non è uno schema definitivo, sono molto interessato a conoscere
sistemi migliori.
** TODO Organizzazione della discussione
Capire meglio quali sono i canali tramite cui tenersi in contatto e/o fare
pair-programming. Magari organizzare una discussione corale tra tutti gli
interessati per fare brainstorming collettivo.
* Problemi di principio
** Euristiche della presentazione dei concetti
*** TODO Import propri / Import impropri
Uno dei problemi che sto avendo nel codice è come ottenere l'import di tutti gli
elementi di un modulo che non sono a loro volta esportati da altri moduli. Ad
esempio, `Control.Lens` esporta grandi porzioni di librerie con cui l'utente è
già familiare, e quindi sarebbe ingiusto includerle nella nostra analisi
** Punti di entrata/uscita per le librerie
** Costruttori/Distruttori per funzioni
** TODO Organizzazione generale della libreria
Struttura dei moduli e dello scope della libreria in generale.
** TODO Definizione di obiettivi preliminari
Quali sono le funzioni che dovremmo sviluppare per prime?
